### ISSUE TITLE
ConcurrentModificationException when starting batch run

### ISSUE THREAD

**Issue by badvision** [Adobe-Consulting-Services/curly#23]
Exception in thread "JavaFX Application Thread" java.util.ConcurrentModificationException
        at java.util.AbstractList$Itr.checkForComodification(Unknown Source)
        at java.util.AbstractList$Itr.next(Unknown Source)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.reduce(Unknown Source)
        at com.adobe.ags.curly.model.RunnerResult.recalculatePercentComplete(RunnerResult.java:122)

**Comment by muralipendyala** [comment]
Hi badvision, is this issue fixeD? I am observing this error while running in batches.

**Comment by badvision** [comment]
I can't remember but I can tell you it's harmless -- it just affects the percentage completion calculation.

**Comment by muralipendyala** [comment]
Yeah. I just checked aem and it has all the values as expected. Only the logger showed wrong value ! Thanks 

Thanks,
Murali

**Comment by badvision** [comment]
Sorry if it inconvenienced you, keep a watch on the repo and I'll make it a
point to get to that issue next.

**Comment by badvision** [comment]
OK I have fixed this.  Just needed to synchronize a few things to avoid race conditions.
