### ISSUE TITLE
MacOS Mojave / OpenJDK11 action list button trigger error

### ISSUE THREAD

**Issue by dfparker2002** [Adobe-Consulting-Services/curly#33]
**Report**
When one clicks "Action (tab) | Add action (button)" no actions listed, no modal appears

**ENV** macos mojave v10.14.6 (18G87)
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+11)
OpenJDK 64-Bit Server VM (build 11.0.8+11, mixed mode)

**Error**
Caused by: java.lang.NullPointerException
at com.adobe.ags.curly.model.ActionUtils.lambda$isFavorite$0(ActionUtils.java:99)
at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
at com.adobe.ags.curly.model.ActionUtils.isFavorite(ActionUtils.java:99)
at com.adobe.ags.curly.model.ActionUtils.isFavorite(ActionUtils.java:93)
at com.adobe.ags.curly.controller.ActionPanelController.lambda$initialize$0(ActionPanelController.java:106)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
at com.adobe.ags.curly.controller.ActionPanelController.initialize(ActionPanelController.java:106)
... 81 more

**Comment by badvision** [comment]
Did you create an action and leave the name blank?  Not sure how else the code would throw a null-pointer exception on that line.

**Comment by badvision** [comment]
I'm not able to do any kind of release build this week, but if you'd like to try this out I've pushed a fix for this issue to the main branch.

**Comment by dfparker2002** [comment]
@badvision No list of actions were available.
Comparing MacOS/OpenJDK to Windows/OracleJDK a default list of actions was available in Win/OraJDK11 and I could add custom actions.

**Comment by badvision** [comment]
Can you confirm if you've left a name blank somewhere as per my first comment?  Also, can you confirm that you're still seeing the problem with the latest code I just checked in?  I didn't update the release build, you'll have to use `mvn install` to build a fresh copy of the app.  In the present code, I don't see how it can throw the same null pointer error you reported initially.

**Comment by badvision** [comment]
(sorry, didn't mean to click the "close" button)
